version: '3'

volumes:
    mongo-keys:

networks:
  replica-set:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.16.0/24

services:
    keys:
        image: depop/openssl-bats
        volumes:
            - mongo-keys:/mongo-conf
        command: 'bin/bash -c "openssl rand -base64 742 > /mongo-conf/mongodb-keyfile; chmod 600 /mongo-conf/mongodb-keyfile; chown 999 /mongo-conf/mongodb-keyfile"'

#setup config servers

    mongo-cfg-2:
        container_name: "mongo-cfg-2"
        image: mongo:4.0.1
        networks: 
            replica-set:
        ports:
            - "30102:27017"
        volumes:
            - mongo-keys:/opt/keyfile
        command: 'bin/bash -c "chown mongodb /opt/keyfile/mongodb-keyfile; mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet cnf-serv --configsvr --port 27017 --oplogSize 16 --bind_ip_all --noprealloc --smallfiles"'
        env_file:
            - ./mongod.env
        restart: always

    mongo-cfg-3:
        container_name: "mongo-cfg-3"
        image: mongo:4.0.1
        networks: 
            replica-set:
        ports:
            - "30103:27017"
        volumes:
            - mongo-keys:/opt/keyfile
            #- "./scripts/:/docker-entrypoint-initdb.d/"
        command: 'bin/bash -c "chown mongodb /opt/keyfile/mongodb-keyfile; mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet cnf-serv --configsvr --port 27017 --oplogSize 16 --bind_ip_all --noprealloc --smallfiles"'
        env_file:
            - ./mongod.env
        restart: always

    mongo-cfg-1:
        container_name: "mongo-cfg-1"
        image: mongo:4.0.1
        networks: 
            replica-set:
        ports:
            - "30101:27017"
        volumes:
            - mongo-keys:/opt/keyfile
            - ./scripts:/scripts
        command: 'bin/bash -c "chown mongodb /opt/keyfile/mongodb-keyfile; mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet cnf-serv --configsvr --port 27017 --oplogSize 16 --bind_ip_all --noprealloc --smallfiles"'
        env_file:
            - ./mongod.env
        restart: always

#setup replica set

    mongo-1-2:
        container_name: "mongo-1-2"
        image: mongo:4.0.1
        ports:
            - "30012:27017"
        volumes:
            - mongo-keys:/opt/keyfile
            - ./data:/data
            #- "./scripts:/docker-entrypoint-initdb.d/"
        env_file:
            - ./mongod.env
        depends_on:
            - "mongo-cfg-1"
            - "mongo-cfg-2"
            - "mongo-cfg-3"
            - "keys"
        command: 'bin/bash -c "chown mongodb /opt/keyfile/mongodb-keyfile; mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --shardsvr --replSet rs1  --oplogSize 16 --bind_ip_all --noprealloc --smallfiles"'
        restart: always

    mongo-1-3:
        container_name: "mongo-1-3"
        image: mongo:4.0.1
          
        ports:
            - "30013:27017"
        volumes:
            - mongo-keys:/opt/keyfile
            - ./data:/data
            #- "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
        env_file:
            - ./mongod.env
        depends_on:
            - "mongo-cfg-1"
            - "mongo-cfg-2"
            - "mongo-cfg-3"
            - "keys"
        command: 'bin/bash -c "chown mongodb /opt/keyfile/mongodb-keyfile; mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --shardsvr --replSet rs1  --oplogSize 16 --bind_ip_all --noprealloc --smallfiles"'
        restart: always 

    mongo-1-1:
        container_name: "mongo-1-1"
        image: mongo:4.0.1
          
        ports:
            - "30011:27017"
        volumes:
            - mongo-keys:/opt/keyfile
            - ./data:/data
            - ./scripts:/scripts
        env_file:
            - ./mongod.env
        depends_on:
            - "mongo-cfg-1"
            - "mongo-cfg-2"
            - "mongo-cfg-3"
            - "keys"
        command: 'bin/bash -c "chown mongodb /opt/keyfile/mongodb-keyfile; mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --shardsvr --replSet rs1  --oplogSize 16 --bind_ip_all --noprealloc --smallfiles"'
        restart: always

#mongos

    mongo-router:
         container_name: "mongo-router"
         image: mongo:4.0.1
         ports:
             - "30001:27017"
         volumes:
             - mongo-keys:/opt/keyfile
             - ./scripts:/scripts
         env_file:
             - ./mongod.env
         depends_on:
             - "keys"
         links:
             - mongo-cfg-1:mongo-cfg-1
             - mongo-cfg-2:mongo-cfg-2
             - mongo-cfg-3:mongo-cfg-3
             - mongo-1-1:mongo-1-1
             - mongo-1-2:mongo-1-2
             - mongo-1-3:mongo-1-3
         command: 'bin/bash -c "chown mongodb /opt/keyfile/mongodb-keyfile; mongos --keyFile /opt/keyfile/mongodb-keyfile --configdb cnf-serv/mongo-cfg-1:27017,mongo-cfg-2:27017,mongo-cfg-3:27017 --port 27017 --bind_ip_all"'
         restart: always
